"""Migration

Revision ID: c5d1811712ca
Revises: 
Create Date: 2024-02-22 15:46:45.165439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5d1811712ca'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('level',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('difficult', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exercise',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cf_id', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('count_solved', sa.Integer(), server_default='0', nullable=False),
    sa.Column('difficult', sa.Integer(), server_default='0', nullable=False),
    sa.Column('task', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['difficult'], ['level.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercise_topic_id'), 'exercise', ['topic_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exercise_topic_id'), table_name='exercise')
    op.drop_table('exercise')
    op.drop_table('level')
    op.drop_table('category')
    # ### end Alembic commands ###
